/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './index.html'],
  theme: {
    colors: {
      // Colors provided
      // Main colors
      main_green: '#48763C',
      main_blue: '#153E79',
      // Secondary colors
      secondary_lime: '#B9D547',
      secondary_darkteal: '#006779',
      secondary_teal: '#3EB0C8',
      secondary_orange: '#DE7D3B',
      secondary_lightgreen: '#CDD6CF',
      secondary_lightblue: '#A9CEEB',
      // Icon colors
      icon_camping: '#2DA649',
      icon_activities: '#EE2347',
      icon_amenities: '#2C439B',
      // Trail colors
      trail_equine: '#C17D12',
      trail_roanokeriver: '#726D82',
      trail_hawriver: '#55848F',
      trail_danriver: '#FFCF01',
      trail_overmountainvictory: '#D92B2F',
      trail_wildernessgateway: '#0078AF',
      trail_hickorynutgorge: '#A1946E',
      trail_northernpeaks: '#6A3935',
      trail_eastcoastgreenway: '#9ACA3C',
      trail_fontaflora: '#853E86',
      trail_mountainstosea: '#EE7624',
      trail_deepriver: '#E11F8F',
      trail_yadkinriver: '#007579',
      trail_frenchbroadriver: '00A851',

      // Supporting colors
      supporting_inactiveblue: '#1B365D',
      supporting_lightblue: '#D3E1EF',
      supporting_darkgray: '#49454F',
      supporting_bluegray: '#94B2B7',
      supporting_lightgray: '#D9D9D9',
      supporting_lightorange: '#E3C7B4',
      supporting_terracotta: '#C15728',

      // System colors
      system_black: '#000000',
      system_white: '#FFFFFF',
      system_gray: '#8E8E93',
      system_red: '#FF3B30',
      system_blue: '#007AFF',
    },
    fontSize: {
      h1: '64px',
      h2: '36px',
      h3: '24px',
      h4: '24px',
      h5: '14px',
      script: '96px',
      p: '18px',
      pm: '14px',
      pl: '40px',
      b: '24px',
    },
    lineHeight: {
      h1: '55px',
      h2: '32px',
      h3: '32px',
      h4: '20px',
      h5: '22px',
      script: '32px',
      p: '22px',
      pm: '12px',
      pl: '45px',
      b: '22px',
    },
    fontWeight: {
      h1: 'heavy',
      h2: 'bold',
      h3: 'bold',
      h4: 'semibold',
      h5: 'bold',
      script: 'regular',
      p: 'semibold',
      pm: 'regular',
      pl: 'semibold',
      b: 'semibold',
    },
    fontFamily: {
      h1: ['var(--font-NWH)'],
      h2: ['var(--font-NWB)'],
      h3: ['var(--font-NWB)'],
      h4: ['var(--font-SSPS)'],
      h5: ['var(--font-NWB)'],
      p: ['var(--font-SSPS)'],
      pm: ['var(--font-SSPR)'],
      pl: ['var(--font-SSPS)'],
      b: ['var(--font-SSPS)'],
      script: ['var(--font-Norican)'],
    },
  },
  plugins: [],
};
