services:

  nginx:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - type: bind
        source: ${PWD}/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - frontend
      - backend
  # asp.net web application backend
  backend: 
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Deployment
    depends_on:
      db:
        condition: "service_healthy"
  # frontend
  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
      additional_contexts:
        - root=.
    ports:
      - "${FE_PORT}:80"
  # mariadb
  db: 
    container_name: database
    image: mariadb:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  mariadb_data: