services:
  # mariadb
  db: 
    container_name: database
    image: mariadb:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network
  
  # asp.net web application backend
  backend: 
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - API_PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - app-network
  
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:latest
    container_name: nginx
    ports:
      - "${VITE_API_HTTP_PORT}:80"
      - "${VITE_API_HTTPS_PORT}:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: