POST {{host}}/products
Authorization: Bearer hello
Content-Type: application/json

{
"Name": "MacBook Pro MЗ Maxy",
"Category": "Electronics",
"SubCategory": "Laptops"
}

###
GET {{host}}/products/cd8a1485-59a5-4663-9ff6-995bf62ed120