@username=testUsername
@password=RandomPassword

### Valid
POST {{backend-uri}}/auth/register/
Content-Type: application/json

{
    username: {{username}},
    password: {{password}}
}

### Invalid - User already created
POST {{backend-uri}}/auth/register/
Content-Type: application/json

{
    username: {{username}},
    password: {{password}}
}