# This script dumps a list of all the files in the frontend/public directory into
# a .ts file that can be used to precache the files in the service worker.

PUBLIC_DIR="./frontend/public"
FILE_PATH="./frontend/src/lib/cache/precached-files.ts"
echo "CURRENT DIR: $(pwd)"

# Remove the file if it exists
if [ -f $FILE_PATH ]; then
    rm $FILE_PATH
fi

# Get the list of files in the frontend/public directory but remove the leading ./frontend/public
FILES=$(find "$PUBLIC_DIR" -type f | sed "s|^$PUBLIC_DIR||")

# Add a message to the top of the file
echo "// This file is automatically generated by the update-precached-files.sh script" > "$FILE_PATH"
echo "// last updated on $(date)" >> "$FILE_PATH"
echo "\n" >> "$FILE_PATH"

echo "export const precachedFiles = [" >> "$FILE_PATH"

# Loop through the files and add them to the .ts file
while IFS= read -r FILE; do
    echo "  '$FILE'," >> "$FILE_PATH"
done <<< "$FILES"

echo "];" >> "$FILE_PATH"

# Print the number of files in the .ts file
echo "Number of files in $FILE_PATH: $(wc -l < "$FILE_PATH")"
