name: Docker Compose Test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  pull_request_target:
    branches: '**'

jobs:
  Test-Docker-Compose:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'
        ssh-known-hosts: 'github.ncsu.edu ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy5K6oZoBJ881aKKkon5MB016unAgciPVqNAlFY6PWtbUd7qJEwbJJAtxZcY43UmB8x4SW8yjqLGeQDEjioDkYY/Ml58Sh+gzAdeMeloGI2uwgVw77bGvcREAZ8s/lpx3D48XtvbS/IU4CgOO7RcMFsOH0y4jVX0LDdDxKLVXu/mUxnrqB8d/NtaZjOeI1b38LxFpfF6RVD7MBC9xhuZUcofVLQMhZq+OZ85xBxqb8UV5Ujp5hPbjO2uBDf3F1G0VLZko8W6LIiJaeBrEVl2UhQR2NDX5w7sUPg9D9mRWDQvIws1C887XeyF84cxkshFzuqbbtnGPVDxNpjMnDoWsN'

    - name: Generate certs
      run: |
        chmod +x setup-dev-certs.sh
        ./setup-dev-certs.sh

    - name: Create .env file
      run: |
        echo 'DB_HOST=${{secrets.DB_HOST}}' > .env
        echo 'DB_PORT=${{secrets.DB_PORT}}' >> .env
        echo 'DB_PASSWORD=${{secrets.DB_PASSWORD}}' >> .env
        echo 'DB_DATABASE=${{secrets.DB_PROD_DATABASE}}' >> .env
        echo 'API_PORT=${{secrets.API_PORT}}' >> .env
        echo 'FE_PORT=${{secrets.FE_PORT}}' >> .env

    - name: Build and run Docker Compose
      run: |
        docker-compose build
        docker-compose up -d
      
    - name: Wait for containers to be healthy
      run: |
        timeout=120
        elapsed=0
        while [ $elapsed -lt $timeout ]; do
          if docker-compose ps --format json | jq -s '.[] | if type=="array" then . else [.] end | .[] | .State' | grep -qv "running"; then
            echo "Waiting for containers to be ready..."
            sleep 5
            elapsed=$((elapsed+5))
          else
            echo "All containers are running!"
            exit 0
          fi
        done
        echo "Timeout reached. Not all containers are running."
        docker-compose logs
        exit 1

    - name: Shut down Docker Compose
      if: always()
      run: |
        cd backend
        docker-compose down
