name: Jest Tests

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  pull_request_target:
    branches: '**'

jobs:
  Run-Jest-Tests:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'
        ssh-known-hosts: 'github.ncsu.edu ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy5K6oZoBJ881aKKkon5MB016unAgciPVqNAlFY6PWtbUd7qJEwbJJAtxZcY43UmB8x4SW8yjqLGeQDEjioDkYY/Ml58Sh+gzAdeMeloGI2uwgVw77bGvcREAZ8s/lpx3D48XtvbS/IU4CgOO7RcMFsOH0y4jVX0LDdDxKLVXu/mUxnrqB8d/NtaZjOeI1b38LxFpfF6RVD7MBC9xhuZUcofVLQMhZq+OZ85xBxqb8UV5Ujp5hPbjO2uBDf3F1G0VLZko8W6LIiJaeBrEVl2UhQR2NDX5w7sUPg9D9mRWDQvIws1C887XeyF84cxkshFzuqbbtnGPVDxNpjMnDoWsN'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
      
    - name: Install dependencies
      run: |
        cd frontend
        npm install
    
    - name: Run Jest tests
      run: |
        cd frontend
        NODE_OPTIONS=--max-old-space-size=4096 npm test
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./frontend/coverage/lcov.info
    
    - name: Upload Coverage Report XML
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report.xml
        path: ./frontend/coverage/**.xml
    